Added Docs and Examples!
ngrx/db pull request #16
Opened 2017-02-20 18:26 UTC by JimTheMan

Ngrx is an amazing Reactive-Redux implementation for Angular 2. Ngrx/db is an important tool our toolbag for preserving the state when the page is closed or refreshed. This repo has gotten NO love at all in terms of the README, and **a lot** of people have been / still are very confused about it. Imo we should all just start using it and work out the bugs (if there are any) when people open issues, just like any other project. 

Anyway, I'm open to feedback and criticism if anything I wrote is totally wrong. Just let me know or change it.

Thanks,
Jimbo

2017-02-20 18:34 UTC, MikeRyanDev requested changes

2017-02-20 18:34 UTC, MikeRyan52 commented on README.md
> +Most browsers have a local data storage mechanism called IndexedDB that allows your application to persist data after the browser is closed or refreshed. Ngrx/db is a library that provides a convenie
Instead of "Ngrx/db" lets go with "@ngrx/db" throughout

2017-02-20 18:50 UTC, JimTheMan commented
ok. 👍  

I just changed to my branch to have the all lowercase capitalization ngrx/db.

2017-02-21 02:20 UTC, michaeljota commented
I'm just watching this, but `.idea` folder is necessary? Can/Should it be removed?

2017-02-21 02:58 UTC, JimTheMan commented
Ah sorry. I didn't realize I added that. It's an artifact created by WebStorm / intellij. You can delete it. :+1

2017-02-21 11:53 UTC, e-cloud commented
add a rule in .gitignore will avoid it.

2017-02-21 16:50 UTC, JimTheMan commented
ok. I just deleted the idea folder so it's no longer included in this PR. :)

2017-02-25 18:13 UTC, JimTheMan commented
Hey, how is it looking now? Can we merge this? :)

2017-03-03 15:50 UTC, JimTheMan commented
Please guys, the entire world hates us for this embarrassing state of the current readme.

![_ngrx_db_-_gitter](https://cloud.githubusercontent.com/assets/5354163/23557772/305cc1e2-ffff-11e6-861d-82ce76d0cdfb.png)

2017-03-03 15:50 UTC, JimTheMan commented
Can someone merge this?

2017-03-03 17:02 UTC, michaeljota commented
I'm not a collaborator or anything, but this seems more like an internal project, that something that someone else could really use. 

It looks really good, but I don't think this is the right time to change the readme yet.

2017-03-03 17:08 UTC, JimTheMan commented
@michaeljota 

I'm assuming you mean "**_not_** something that someone else could really use." ?

And if so, why on earth would you think that???

2017-03-03 17:55 UTC, michaeljota commented
You may want something, yet be unable to use it. As this.

2017-03-03 18:10 UTC, JimTheMan commented
What evidence do you have that this is unable to be used? I am using it right now, as are many other devs I know:


- https://github.com/xlozinguez/angular-nyc-advanced-ngrx
- https://github.com/btroncone/ngrx-examples
- https://github.com/dereklin/ng-ws-ngrx-hmr
- https://github.com/JimTheMan/t2

2017-03-03 20:55 UTC, michaeljota commented
The fact that someone _is_ using it, it's not proof to say it _should_ be used.

2017-03-03 21:36 UTC, JimTheMan commented
Well we are all using it, and it's working fine. I'm even using in production for one app...

What would be sufficient proof that it _should_ be used?

BTW anyone who actually wrote this library (@mikeryan52 @brandonroberts @robwormald) feel free to chime in...

2017-03-04 00:51 UTC, michaeljota commented
Nope. I mean, the people who actually wrote this say "don't use me yet".

2017-03-04 00:53 UTC, JimTheMan commented
If a github README told you to jump off a bridge, would you do it? ;)

On Mar 3, 2017 7:51 PM, "Michael De Abreu" <notifications@github.com> wrote:

> Nope. I mean, the people who actually wrote this say "don't use me yet".
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ngrx/db/pull/16#issuecomment-284110707>, or mute the
> thread
> <https://github.com/notifications/unsubscribe-auth/AFGysxplirKm9FPCWKfFINccu8MF9K6Jks5riLWCgaJpZM4MGfv->
> .
>

2017-03-04 05:03 UTC, michaeljota commented
🙄🙄🙄🙄 You must be the rudest person I ever chat here in Github. They have no obligation to even have their own repo documented in anyhow. Thanks you for your README, if that's what you want, but I hope this gets closed, along with your duplicate issue #16 :).

2017-03-04 05:14 UTC, JimTheMan commented
@michaeljota Please stop trolling this thread.

2017-03-08 09:49 UTC, somombo commented on README.md
> +## __**USE ME NOW!**__
I don't think this is necessary, the fact that "Don't use me yet." was removed is sufficient to indicate it is now usable

2017-03-08 09:58 UTC, somombo commented
Agreed, @michaeljota your personal attacks don't add any value to this or any project. I think @JimTheMan  should be commended for atleast trying to contribute something. And the open source maintainers do have some level of obligation, IMO to atleast respond "we have seen your comments/PR, but we are busy at the moment and will respond at such and such a time" 

Good work @JimTheMan

2017-03-08 13:05 UTC, michaeljota commented
@somombo Just for clarification, I'm not personal attacking him. I'm watching this whole repo, so I can track progress. If you look in issues, you could see an open issue that only refers to merge this, still open, PR. 

So I'm just leading to the fact that the people behind this project may not want to make this public usable _yet_, and this guy keep pushing to merge something as it is some kind of obligation for this organization to merge _every_ PR.

I just want a notification here to be related with progress. I'm sorry if there is any misunderstanding.

2017-03-25 10:14 UTC, varghesep commented
@JimTheMan's opinions are valid. A coordinated effort can make it usable.

2017-03-31 23:19 UTC, robwormald commented
@JimTheMan thanks for the PR. i'm merging it now and then i'll be migrating this repo to the monorepo @ https://github.com/ngrx/platform 

to everyone commenting in here:

ngrx/db began and remains an experimental thing. IndexedDB is a non-trivial API, and notoriously difficult to use consistently across different browsers. I'm not comfortable committing to the full support we give the other ngrx projects until it's been much more extensively tested and proven, which is why it has not previously had docs or a readme. 

I, frankly, don't have the hours in the day to make that happen right now. If the community would like to make that happen, I am all for it and would welcome your help.

2018-01-11 12:38 UTC, MattiJarvinen commented
@robwormald hmm.... about migrating to monorepo? What would be needed? Do we get a roadmap what PRs have to happen? List of issues with IndexedDB to be tested etc?

2019-09-21 04:04 UTC, closed without merging